name: Build & Deploy LyneApp Spring Boot Application

on:
  push:
    branches:
      - authentication-and-onboarding

jobs:
  build-deploy:
    name: Build & Deploy LyneApp Spring Boot Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml -Dmaven.test.skip=true

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lyneapp-backend:latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lyneapp-backend:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Configure AWS ECS
        run: |
          aws ecs configure --region ca-central-1 --cluster lyneapp-backend-cluster --default-launch-type EC2

      - name: Deploy to AWS ECS
        run: |
          aws ecs update-service --region ca-central-1 --cluster lyneapp-backend-cluster --service lyneapp-backend-service --force-new-deployment